---
- name: Setup Web Server
  hosts: webservers
  become: yes
  vars:
    packages:
      - nginx
      - ufw
  
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
    
    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
    
    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22
        - 80
        - 443
    
    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    
    - name: Create custom index page
      copy:
        content: |
          <html>
          <head><title>Ansible Lab</title></head>
          <body>
          <h1>Welcome to {{ inventory_hostname }}</h1>
          <p>This server was configured by Ansible!</p>
          <p>Server IP: {{ ansible_default_ipv4.address }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      notify: restart nginx
  
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted